name: 📦 Project 
description: Project for Artoo-Detoo
title: " Project : "
labels:
  - "Type : Project :package:"
body:
  - type: markdown
    attributes:
      value:  📦 Project 
  - type: textarea
    attributes:
      label: Project/APP
      description: A clear and concise description of what the problem is.
      placeholder: I'm always frustrated when '…'
    validations:
      required: true
  - type: textarea
    attributes:
      label: Featute/Task List
      description: A clear and concise description of what you want to happen.
      placeholder: "- [] task 1"
    validations:
      required: true
