[user]
name = ""
email = ""

[remote]
upstream = ""
default = "origin"

[config]

[branch.main]
prefix = ""
url = ""
default = "main"

[branch.develop]
prefix = ""
url = ""
default = "develop"

[branch.feature]
prefix = "feature/"
url = ""
default = ""

[branch.bugfix]
prefix = "bugfix/"
url = ""
default = ""

[branch.hotfix]
prefix = "hotfix/"
url = ""
default = ""

[branch.release]
prefix = "release/"
url = ""
default = ""

[branch.support]
prefix = "support/"
url = ""
default = ""

[branch.version]
prefix = "v"
url = ""
default = ""

[branch.task]
prefix = "task/"
url = ""
default = ""

[branch.default]
prefix = ""
url = ""
default = ""

[remote.origin]
main = ""
develop = ""
feature = ""
hotfix = ""
release = ""
support = ""

[remote.prefix]
origin = ""
upstream = ""

[remote.url]
origin = ""
upstream = ""
